version: '3.8'

services:
  nextchat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextchat-app
    ports:
      - "13000:3000"
    environment:
      # 基础配置
      - NODE_ENV=production
      - PORT=3000
      
      # API 配置 - 请根据需要修改
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CODE=${CODE:-}
      - BASE_URL=${BASE_URL:-}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID:-}
      
      # Google AI 配置
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GOOGLE_URL=${GOOGLE_URL:-}
      
      # Anthropic Claude 配置
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - ANTHROPIC_URL=${ANTHROPIC_URL:-}
      
      # Azure OpenAI 配置
      - AZURE_URL=${AZURE_URL:-}
      - AZURE_API_KEY=${AZURE_API_KEY:-}
      - AZURE_API_VERSION=${AZURE_API_VERSION:-}
      
      # 百度文心一言配置
      - BAIDU_API_KEY=${BAIDU_API_KEY:-}
      - BAIDU_SECRET_KEY=${BAIDU_SECRET_KEY:-}
      - BAIDU_URL=${BAIDU_URL:-}
      
      # 字节跳动豆包配置
      - BYTEDANCE_API_KEY=${BYTEDANCE_API_KEY:-}
      - BYTEDANCE_URL=${BYTEDANCE_URL:-}
      
      # 阿里通义千问配置
      - ALIBABA_API_KEY=${ALIBABA_API_KEY:-}
      - ALIBABA_URL=${ALIBABA_URL:-}
      
      # 腾讯混元配置
      - TENCENT_SECRET_ID=${TENCENT_SECRET_ID:-}
      - TENCENT_SECRET_KEY=${TENCENT_SECRET_KEY:-}
      
      # 月之暗面 Kimi 配置
      - MOONSHOT_API_KEY=${MOONSHOT_API_KEY:-}
      - MOONSHOT_URL=${MOONSHOT_URL:-}
      
      # 智谱 GLM 配置
      - IFLYTEK_API_KEY=${IFLYTEK_API_KEY:-}
      - IFLYTEK_URL=${IFLYTEK_URL:-}
      
      # 其他配置
      - CUSTOM_MODELS=${CUSTOM_MODELS:-}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-}
      - DISABLE_GPT4=${DISABLE_GPT4:-}
      - ENABLE_BALANCE_QUERY=${ENABLE_BALANCE_QUERY:-}
      - DISABLE_FAST_LINK=${DISABLE_FAST_LINK:-}
      - WHITE_WEBDAV_ENDPOINTS=${WHITE_WEBDAV_ENDPOINTS:-}
      - HIDE_USER_API_KEY=${HIDE_USER_API_KEY:-}
      - DISABLE_FAST_LINK=${DISABLE_FAST_LINK:-}
      
    volumes:
      # 可选：持久化数据
      - nextchat_data:/app/data
    restart: unless-stopped
    networks:
      - nextchat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nextchat_data:
    driver: local

networks:
  nextchat-network:
    driver: bridge
