version: '3.8'

services:
  nextchat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextchat-app
    ports:
      - "13000:3000"
    env_file:
      - .env
      
    volumes:
      # 可选：持久化数据
      - nextchat_data:/app/data
    restart: unless-stopped
    networks:
      - nextchat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nextchat_data:
    driver: local

networks:
  nextchat-network:
    driver: bridge
